# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
      - 202012
  paths:
    exclude:
      - .github

pr:
  branches:
    include:
      - master
      - 202012
  paths:
    exclude:
      - .github

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

stages:
- stage: Build
  pool: sonicbld
  jobs:
  - job: Build
    steps:
    - script: |
        echo "Build"
      displayName: Build script
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true
        architecture: 'x64'
    - script: |
        pip --version
      displayName: test
    - task: PythonScript@0
      inputs:
        scriptSource: 'inline'
        script: 'print(1)'